kafka {
  bootstrap-servers = "santa-cruz-kafka-1.iainschmitt.com:10000,santa-cruz-kafka-1.iainschmitt.com:10001,"

  ssl {
    security-protocol = "SSL"
    keystore-type = "JKS"
    keystore-location = "/Users/iain/code/infra-grab-bag/ssl/santa-cruz-kafka-1/peer-3/peer.keystore.jks"
    keystore-password = "810b0d1483311ca51bcc743cd4e6e5df"
    key-password = "810b0d1483311ca51bcc743cd4e6e5df"
    truststore-type = "JKS"
    truststore-location = "/Users/iain/code/infra-grab-bag/ssl/santa-cruz-kafka-1/peer-3/peer.truststore.jks"
    truststore-password = "810b0d1483311ca51bcc743cd4e6e5df"
    protocol = "TLSv1.2"
    enabled-protocols = "TLSv1.2"
    endpoint-identification-algorithm = "" # My cert scripts are wrong and I don't want to fix them yet
  }
}

nginx-logs-topic = "nginx-logs"
database = "/Users/iain/code/personal-web-analytics/dev.app.sqlite"
backup-bucket = "dev-personal-web-analytics"