kafka {
  bootstrap-servers = "santa-cruz-kafka-0.iainschmitt.com:9093"

  ssl {
    security-protocol = "SSL"
    keystore-type = "JKS"
    keystore-location = "/Users/iain/code/infra-grab-bag/ssl/peer-1/peer.keystore.jks"
    keystore-password = "b9abd3a2badb5551c401814dad930e92"
    key-password = "b9abd3a2badb5551c401814dad930e92"
    truststore-type = "JKS"
    truststore-location = "/Users/iain/code/infra-grab-bag/ssl/peer-1/peer.truststore.jks"
    truststore-password = "b9abd3a2badb5551c401814dad930e92"
    protocol = "TLSv1.2"
    enabled-protocols = "TLSv1.2"
  }
}

nginx-logs-topic = "nginx-logs"
database = "/Users/iain/code/personal-web-analytics/dev.app.sqlite"