kafka {
  bootstrap-servers = "santa-cruz-kafka-1.iainschmitt.com:10000,santa-cruz-kafka-1.iainschmitt.com:10001,"

  ssl {
    security-protocol = "SSL"
    keystore-type = "JKS"
    keystore-location = "/certs/peer.keystore.jks"
    keystore-password = "b4c3fde5acf8cc903c9a27634d07c028"
    key-password = "b4c3fde5acf8cc903c9a27634d07c028"
    truststore-type = "JKS"
    truststore-location = "/certs/peer.truststore.jks"
    truststore-password = "b4c3fde5acf8cc903c9a27634d07c028"
    protocol = "TLSv1.2"
    enabled-protocols = "TLSv1.2"
    endpoint-identification-algorithm = "" # My cert scripts are wrong and I don't want to fix them yet
  }
}

nginx-logs-topic = "nginx-logs"
database = "/data/prod.app.sqlite"
backup-bucket = "prod-personal-web-analytics"
